// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbrxuvjaytwkchpzgsqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpicnh1dmpheXR3a2NocHpnc3FpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MjQ4MjMsImV4cCI6MjA2NTAwMDgyM30.rjnCj0h-N22Btoi8FKGLhXZyaAIpea2cadokoxYKXfg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);